### ISSUE TITLE
documentation error: default port

### ISSUE THREAD

**Issue by teo1978** [Sensebloom/OSCeleton#10]
The help from "osceleton -h" says:

  -a <addr>  Address to send OSC packets to (default: localhost).
  -p <port>  Port to send OSC packets to (default: 7110).

However, if I don't explicitly specify a port and listen to port 7110 I don't get anything. If I specify a port with the -p option (whether it is 7110 or another one) and I listen to that port then I do get data.

So I guess either the default port is NOT 7110, or it doesn't send data at all unless you specify a port.

**Comment by teo1978** [comment]
Well it's strange, because when called without specifying a port it actually says
"Configured to send OSC messges to 127.0.0.1:7110"
However it isn't sending anything to that port.

**Comment by MylesBorins** [comment]
So I think I have fixed the problem... I have submitted a pull request, but you are welcome to try out my fork if you like
