### ISSUE TITLE
joint and orientation data mixed

### ISSUE THREAD

**Issue by teo1978** [Sensebloom/OSCeleton#11]
The readme file says:
### -xt

This option outputs the joint rotation data.
    Address pattern: "/orient"
    Type tag: "sifffffffff"

Instead, orientation data is output with the address "/joint", exactly the same as normal joint data, so you can't distinguish them by the address, you have to distinguish them by the number of elements in the message.

For example you get:

 /joint l_hip 1 372.283 -86.3652 1311.5
 /joint l_hip 1 0.978296 0.12194 0.167531 -0.198848 0.77985 0.593544 -0.0582718 -0.613975 0.787172
 /joint l_knee 1 462.281 -439.326 1042.86
 /joint l_knee 1 0.978296 0.12194 0.167531 -0.198848 0.77985 0.593544 -0.0582718 -0.613975 0.787172
 /joint l_ankle 1 0.978296 0.12194 0.167531 -0.198848 0.77985 0.593544 -0.0582718 -0.613975 0.787172
 /joint l_foot 1 548.818 -778.711 784.554
 /joint r_hip 1 477.07 -66.1017 1131.94
 /joint r_hip 1 0.714734 -0.222359 0.663108 0.0359994 0.958554 0.282628 -0.69847 -0.178132 0.693115
 /joint r_knee 1 460.777 -499.95 1004.02
 /joint r_knee 1 0.714734 -0.222359 0.663108 0.0359994 0.958554 0.282628 -0.69847 -0.178132 0.693115

**Comment by AdbC99** [comment]
Should be fixed with latest update, sorry
