### ISSUE TITLE
Missing argument -lpthread in Makefile (small Issue)

### ISSUE THREAD

**Issue by YggdrasiI** [Sensebloom/OSCeleton#19]
Run 'make' in the main directory fails with
g++ osc_tools/osc2file.c -O3 -Wno-write-strings -Iliblo-0.26-modified liblo-0.26-modified/src/.libs/*.o -o osc2file
liblo-0.26-modified/src/.libs/liblo_la-server_thread.o: In function `lo_server_thread_stop'
[...]/OSCeleton/liblo-0.26-modified/src/server_thread.c:132: undefined reference to`pthread_join'

It's suffice to add the option -lpthread for the entries osc2file, osc2text, file2osc in the makefile to fix it.

System: Ubuntu 10.4
OSCeleton version: commit  730768303d782c81b98e (?)

**Comment by MylesBorins** [comment]
Hey Yggdrasil... if you fork the project you can make the changes to the makefile yourself... and then send a pull request to have it merged with the main code base.

**Comment by textchimp** [comment]
Just to let you know, this unfixed error still caused my build to fail. It looks like there's a pending pull request for the necessary changes to be added?
