### ISSUE TITLE
Ubuntu amd64 - segmentation fault on found a user

### ISSUE THREAD

**Issue by jjbarrows** [Sensebloom/OSCeleton#5]
$ ./osceleton
Configured to send OSC messages to 127.0.0.1:7110
Multipliers (x, y, z): 1.000000, 1.000000, 1.000000
Offsets (x, y, z): 0.000000, 0.000000, 0.000000
OSC Message format: Default OSCeleton format
Initialized Kinect, looking for users...

New User 1
Segmentation fault

**Comment by jjbarrows** [comment]
kitchen mode makes a (slight) difference:

$ ./osceleton -k
Configured to send OSC messages to 127.0.0.1:7110
Multipliers (x, y, z): 1.000000, 1.000000, 1.000000
Offsets (x, y, z): 0.000000, 0.000000, 0.000000
OSC Message format: Kitchen (Animata compatibility)
Initialized Kinect, looking for users...

New User 1
Calibration started for user 1
Calibration failed for user 1
Calibration started for user 1
Calibration complete, start tracking user 1
Segmentation fault

**Comment by tonyfg** [comment]
I pushed a new version today, can you confirm if the issue still happens? Make sure you have both usb cable and the kinect's power supply connected.
Thanks for the report :)

**Comment by jjbarrows** [comment]
Thanks Tonyfg!
confirmed that your fix works great build and run on ubuntu amd64
(runs without seg fault, sends OSC messages)
the model in puredata appears messed up and kinect is only seeing me when very close, not sure where the fault is, as I've only just tested this working version)
-joseph

---

./oscelen  -p 8110 -oy -.5 -ox -.5
Configured to send OSC messages to 127.0.0.1:8110
Multipliers (x, y, z): 1.000000, 1.000000, 1.000000
Offsets (x, y, z): -0.500000, -0.500000, 0.000000
OSC Message format: Default OSCeleton format
Initialized Kinect, looking for users...

New User 1
Calibration started for user 1
Calibration complete, start tracking user 1

## New User 2

OSC messages recieved in puredata:
oscD 8110: /joint neck 1 0.519038 0.136475 0.381807
oscD 8110: /joint l_shoulder 1 0.170025 0.0831545 0.399635
oscD 8110: /joint r_shoulder 1 0.322696 0.189796 0.363979
oscD 8110: /joint torso 1 0.144933 0.17379 0.531055
oscD 8110: /joint l_hip 1 0.191656 0.175226 0.693311
oscD 8110: /joint r_hip 1 0.44334 0.245762 0.668926
oscD 8110: /lost_user 2
oscD 8110: /new_user 2

**Comment by tonyfg** [comment]
If you are having trouble with the kinect detecting you, you can run the niUserTracker sample simultaneously with OSCeleton so you can see the output of the depth sensor ;)

If the model appears messed up you can try playing with the -mx options. Try big values if the joints are too close together, or small values (like 0.5 or 0.1) if the they are too far apart.

**Comment by jjbarrows** [comment]
thanks, fiddling with -mx and -ox I got the figure about right, I still get the occasional seg fault, or the program won't quit with ctrl-c, usually when the user is lost (though it doesn't always report that first) as I walk back to my computer.
but great piece of software, am loving having live skeleton data available to play with!
